Handles virtualenv of not installed, self-compiled Python versions
Nuitka/Nuitka pull request #2613
Opened 2023-12-15 15:19 UTC by flozz

# What does this PR do?

This PR allows Nuitka to work with virtualenvs created from not-installed, self-compiled Python version on Unix systems (tested and works on macOS).

# Why was it initiated? Any relevant Issues?

This PR is related to issue #2611.

# PR Checklist

- [x] Correct base branch selected? Should be `develop` branch.
- [x] Enabled commit hook or executed `./bin/autoformat-nuitka-source`.
- [x] All tests still pass. Check the Developer Manual about `Running the Tests`. There are GitHub
  Actions tests that cover the most important things however, and you are welcome to rely on those,
  but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [ ] Ideally new or changed features have documentation updates.

---

NOTE: I successfully ran all the tests on Linux. On macOS they fail (either on my branch and on `develop`): 

```
+Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
```

2023-12-16 08:32 UTC, kayhayen requested changes
I think the "islink" may not actually be necessary, if you just create the realpath and check it, you will also cover non-virtualenv usage as well, and the code will be not repeating itself, and I think, for Windows you need not exclude it at all, it will be good for detecting that one as well.

2023-12-16 08:35 UTC, kayhayen commented
One merged, I will retry with Windows and see how that helps. The detection of the PythonXY.LIB file kind of does similar things, but probably can be made into redundant code with a correct Python prefix. We might be able to drop the `os.name` exclusion, but I like it for now until it's also attempted.

2023-12-16 08:36 UTC, kayhayen commented
Looks like it can be 1.9 material to me right now, going to merge it to stable.

2023-12-16 15:06 UTC, flozz commented
I updated as requested :)

2023-12-17 13:12 UTC, kayhayen approved these changes

2023-12-17 13:15 UTC, kayhayen commented
Good job, I will actually benefit from this, since so far, when I (very rarely) did try to debug things by changing Python source code, I had to do an install step, that made things more clumsy, but now I expect it to work well.

I am however sceptical that your macOS build will work well for loading extension modules with Nuitka compiled binaries. I have seen problems with that, and mean to extract from somewhere what the proper way is. Ideally on macOS, and I do not know if it's possible, also it would be good to avoid "Python" as a DLL for macOS, for smaller deployments, and just generally because there is no real need for it, at least on Linux that works very well. I know on Windows DLL is required there, but I would assume that is not the case on macOS or is it.

Anyway, I will try it on Linux, and probably even merge to the next hotfix, as it seems very harmless, even if not super urgent stuff.

2023-12-17 13:50 UTC, merged