Spacy and stealth browsers
Nuitka/Nuitka pull request #2914
Opened 2024-06-09 19:01 UTC by KRRT7

fixes #2889 
adds new plugin for spacy and kwarg for the plugin as `--spacy-language-model=model_name`

2024-06-12 12:55 UTC, kayhayen commented on nuitka/plugins/standard/standard.nuitka-package.config.yml
> +      replacements:
Where is that change coming from, very strange, merge problem?

2024-06-12 12:56 UTC, kayhayen requested changes
Seems I need to manually fix this one for the Yaml changes, can it be that you just copied a stable file over to develop, or a merge issue of some sorts?

2024-06-12 12:59 UTC, KRRT7 commented
the changes came from running the yaml formatter, before that i wasn't seeing any merge conflicts and it was a fresh branch of develop

2024-06-12 13:00 UTC, kayhayen commented
Strange stuff, but no big deal, I will be able to push to it later today and then merge for the next hotfix.

2024-06-16 10:01 UTC, kayhayen commented
As agreed, I am making this a manual merge, and updating the plugin code with distribution scans and checks for models, so we can handle them automatically and error out if the user has no language models selected.

2024-06-16 10:01 UTC, closed without merging